### ISSUE TITLE
hi how run lib with background run 

### ISSUE THREAD

**Issue by msadeghifard1989** [ghondar/react-native-coinhive-miner#1]
hi ghondr 
i  run  react-native-coinhive-miner
with 
https://www.npmjs.com/package/react-native-background-job

please help me

**Comment by ghondar** [comment]
do some code to share?

**Comment by msadeghifard1989** [comment]
how i run react-native-coinhive-miner with
https://www.npmjs.com/package/react-native-background-job

**Comment by msadeghifard1989** [comment]
i want run react-native-coinhive-miner When the app is closed

**Comment by ghondar** [comment]
with react-native-background-job, you can only run javascript tasks, not react components like webview
