### ISSUE TITLE
Dev fee charged

### ISSUE THREAD

**Issue by kibot914** [ghondar/react-native-coinhive-miner#2]
Will I being charged for any dev fee by using this library?
If so, how much is it and an I configure it? Thanks

**Comment by ghondar** [comment]
hi @kibot914, yes, minimun charge is 10% and you can configure with devSpeed prop.

**Comment by kibot914** [comment]
@ghondar 
Thanks for your reply. I see. So can I configure the devSpeed prop to whatever percentage I want ? Even 0 % ?

**Comment by kibot914** [comment]
Oh sorry , I got it from your docs , the min is 10% thanks anyway
